### ISSUE TITLE
[Roadmap] SparseML Roadmap Q1 2024

### ISSUE THREAD

**Issue by mgoin** [neuralmagic/sparseml#2081]
## Short-term Work
Issues or PRs that the NM team are planning to tackle for this quarter:
* SparseGPT one-shot pruning for Transformers 
  * [x] Support for text generation LLMs `AutoModelForCausalLM` https://github.com/neuralmagic/sparseml/pull/2010
  * [ ] General model support `AutoModel` https://github.com/neuralmagic/sparseml/pull/2003

* Saving compressed models
  * [ ] Export sparse models w/ sparsity_config to Transformers
  * [ ] Export weight-quantized models w/ quant_config to Transformers
  * [ ] Export W8A8-quantized models w/ quant_config to Transformers

## Long-term Tracked Feature Requests/Issues

**Comment by mgoin** [comment]
Q1 is done!
