### ISSUE TITLE
[Roadmap] SparseML Roadmap Q2 2024

### ISSUE THREAD

**Issue by mgoin** [neuralmagic/sparseml#2216]
## Short-term Work
Issues or PRs that the NM team are planning to tackle for this quarter:

* Dependencies
  * [x] Forkless Transformers https://github.com/neuralmagic/sparseml/pull/2199
  * [x] Upgrade Transformers to latest version https://github.com/neuralmagic/sparseml/pull/2204
  * [x] Upgrade PyTorch to latest version https://github.com/neuralmagic/sparseml/pull/2247 https://github.com/neuralmagic/sparseml/pull/2259
  * [x] Upgrade Pydantic to v2 https://github.com/neuralmagic/sparseml/pull/2248

* SparseGPT one-shot pruning for Transformers 
  * [ ] General model support `AutoModel` https://github.com/neuralmagic/sparseml/pull/2003

* Saving compressed models
  * [x] Export sparse models w/ sparsity_config to Transformers https://github.com/neuralmagic/sparseml/pull/2190
  * [ ] Export weight-quantized models w/ quant_config to Transformers
  * [ ] Export W8A8-quantized models w/ quant_config to Transformers

## Long-term Tracked Feature Requests/Issues
